### ISSUE TITLE
Uploaded files not present in "Edit profile page" on moodle 4.2

### ISSUE THREAD

**Issue by FedFiore** [rezaies/moodle-profilefield_file#10]
I can upload files in profile users custom fields and I can see them and download them on the profile page .../user/profile.php but if I click again the "Edit profile" link on the user profile page the files uploaded before are not present in the page .../user/editadvanced.php and if I click "Update profile" (button present in the same page) the files will be deleted from the user profile page.
This problem was not present on moodle 3.11 but appeared after the update to moodle 4.2.2
I think that on Moodle 4.2 the file management use a new approch, can you update your code for using this plugin on Moodle 4.2?
Thanks in advance!

**Comment by rezaies** [comment]
Thank you for the report. This is now fixed.
