### ISSUE TITLE
Compatibility with recent moodle versions (3.10, 3.11)

### ISSUE THREAD

**Issue by sba-edu** [rezaies/moodle-profilefield_file#8]
Hello,

reading the comments on the [plugin page](https://moodle.org/plugins/profilefield_file), it seems that the plugin is compatible with newer versions of Moodle (at least 3.10).

You may want to adjust the corresponding [compatibility statement](https://moodle.org/plugins/profilefield_file/versions) accordingly.

![file-upload](https://user-images.githubusercontent.com/92781972/138066881-7f6616d6-c84c-4557-ba16-3401357c7fcb.jpg)

**Comment by rezaies** [comment]
Thanks. Done.
